### ISSUE TITLE
 nova hypervisor hostname registration is not fqdn when virt-type=lxd

### ISSUE THREAD

**Issue by zulcss** [lxc/nova-lxd#77]
While I've not picked up on any adverse effect to functionality, I'm raising this for the consistency factor.

When virt-type=lxd, the hypervisor hostnames registered with nova are not fqdns (1, 2, 6).

When virt-type=kvm (default), they are registered with fqdns (3, 4, 5).

    nova-compute-kvm:
      branch: lp:charms/trusty/nova-compute
      num_units: 3
      constraints: mem=4G
      options:
        enable-live-migration: True
        enable-resize: True
        migration-auth-type: ssh
...
    nova-compute-lxd:
      branch: lp:charms/trusty/nova-compute
      num_units: 3
      constraints: mem=4G
      options:
        virt-type: lxd

ubuntu@beisner-bastion:~/bzr/openstack-charm-testing-multi-hypervisor$ nova hypervisor-list
+----+--------------------------------------+
| ID | Hypervisor hostname |
+----+--------------------------------------+
| 1 | juju-beis1-machine-19 |
| 2 | juju-beis1-machine-18 |
| 3 | juju-beis1-machine-16.openstacklocal |
| 4 | juju-beis1-machine-15.openstacklocal |
| 5 | juju-beis1-machine-14.openstacklocal |
| 6 | juju-beis1-machine-17 |
+----+--------------------------------------+

More detail:
http://paste.ubuntu.com/13582658/

**Comment by john5223** [comment]
Did someone change this back after your commit? It's using socket.gethostname again instead of fqdn. 

https://github.com/lxc/nova-lxd/blob/master/nova_lxd/nova/virt/lxd/host.py#L73

**Comment by zulcss** [comment]
Yes I pushed it the wrong tree
